# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1139793b2533c931938b52997f96a099bfec8444c2e48ab640dc90d64694e27a16acba41f65298f5922adf5839368c706e1601537627a5760996f648df10ddf2

test:
  secret_key_base: 4afa379f8b7ee5a9f143a138f76501a8ea938cda477f7ef8da0c34a4df578d9deda34b520385225380ca46a96a1291493552db6f8a538d7aedcbd45318b9f36a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
